Drop golang.org/x/net replace
openstack-k8s-operators/osp-director-operator pull request #1027
Opened 2024-04-15 22:19 UTC by dprince

2024-04-16 05:47 UTC, stuggi approved these changes
/lgtm

2024-04-16 09:44 UTC, compi-migui requested changes

2024-04-16 09:44 UTC, compi-migui commented on go.mod
> -	golang.org/x/net => golang.org/x/net v0.17.0
This replace was originally added to address Rapid Reset ([CVE-2023-39325/CVE-2023-44487](https://pkg.go.dev/vuln/GO-2023-2102)). Seems the resolver ends up with golang.org/x/net v0.21.0 now so that's not needed anymore.

However rather than dropping it I think we need to bump it in order to address [CVE-2023-45288](https://access.redhat.com/security/cve/CVE-2023-45288) which impacts golang.org/x/net/http2 < v0.23.0 per the [golang Vulnerability Report](https://pkg.go.dev/vuln/GO-2024-2687).

2024-04-17 13:30 UTC, stuggi commented on go.mod
> -	golang.org/x/net => golang.org/x/net v0.17.0
@dprince I added a commit to bump to net v0.23.0

2024-04-17 13:34 UTC, stuggi commented
v1.3.x PR https://github.com/openstack-k8s-operators/osp-director-operator/pull/1029

2024-04-18 05:57 UTC, stuggi commented
I think we need this to be in sync with https://github.com/openstack-k8s-operators/osp-director-operator/pull/1029

2024-04-18 13:01 UTC, stuggi approved these changes
/lgtm

2024-04-18 13:05 UTC, merged